"""research workflows

Revision ID: 0002_research_workflows
Revises: 0001_current_schema
Created: 2026-09-29 17:32:52.766656
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_research_workflows"
down_revision: str | None = "0001_current_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lab_templates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_templates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lab_templates_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_lab_templates_name"), ["name"], unique=False)

    op.create_table(
        "lab_automation_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=True),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("request", sa.String(), nullable=False),
        sa.Column("plan", sa.String(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("approval_note", sa.String(), nullable=False),
        sa.Column("output", sa.String(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_automation_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_automation_runs_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_automation_runs_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "lab_evaluation_experiments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("models", sa.JSON(), nullable=False),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_evaluation_experiments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_evaluation_experiments_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "lab_project_policies",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("data_classification", sa.String(), nullable=False),
        sa.Column("allowed_models", sa.JSON(), nullable=False),
        sa.Column("max_run_tokens", sa.Integer(), nullable=False),
        sa.Column("max_run_usd", sa.Float(), nullable=False),
        sa.Column("max_project_usd", sa.Float(), nullable=False),
        sa.Column("max_concurrent_runs", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_table(
        "lab_source_documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("content_sha256", sa.String(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_source_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_source_documents_content_sha256"), ["content_sha256"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_source_documents_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "lab_trace_links",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("relationship", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_trace_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_trace_links_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_trace_links_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_trace_links_target_id"), ["target_id"], unique=False
        )

    op.create_table(
        "lab_evaluation_candidates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("experiment_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("response", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["lab_evaluation_experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_evaluation_candidates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_evaluation_candidates_experiment_id"),
            ["experiment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lab_evaluation_candidates_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "lab_source_excerpts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("locator", sa.String(), nullable=False),
        sa.Column("quote", sa.String(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("quote_sha256", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["lab_source_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_source_excerpts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_source_excerpts_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_source_excerpts_quote_sha256"), ["quote_sha256"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_source_excerpts_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "lab_action_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("meeting_id", sa.String(), nullable=True),
        sa.Column("owner_agent_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("details", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("promoted_task_id", sa.String(), nullable=True),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["lab_meetings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_agent_id"],
            ["lab_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["promoted_task_id"],
            ["lab_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_action_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_action_items_meeting_id"), ["meeting_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_action_items_owner_agent_id"), ["owner_agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_action_items_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_action_items_promoted_task_id"), ["promoted_task_id"], unique=False
        )

    op.create_table(
        "lab_evaluation_scores",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("criterion", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.Column("reviewer", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["lab_evaluation_candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_evaluation_scores", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_evaluation_scores_candidate_id"), ["candidate_id"], unique=False
        )

    op.create_table(
        "lab_task_dependencies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("depends_on_task_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["depends_on_task_id"],
            ["lab_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["lab_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_task_dependencies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_task_dependencies_depends_on_task_id"),
            ["depends_on_task_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lab_task_dependencies_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_task_dependencies_task_id"), ["task_id"], unique=False
        )

    op.create_table(
        "lab_task_source_links",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["lab_source_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["lab_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_task_source_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_task_source_links_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_task_source_links_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_task_source_links_task_id"), ["task_id"], unique=False
        )

    op.create_table(
        "lab_meeting_outcomes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("meeting_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("decisions", sa.JSON(), nullable=False),
        sa.Column("disagreements", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["lab_meetings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["lab_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_meeting_outcomes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_meeting_outcomes_meeting_id"), ["meeting_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_meeting_outcomes_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_meeting_outcomes_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "lab_model_calls",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("system_prompt", sa.String(), nullable=False),
        sa.Column("user_prompt", sa.String(), nullable=False),
        sa.Column("policy_snapshot", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["lab_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["lab_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_model_calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lab_model_calls_agent_id"), ["agent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lab_model_calls_model"), ["model"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_lab_model_calls_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_lab_model_calls_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lab_model_calls_stage"), ["stage"], unique=False)

    op.create_table(
        "lab_claims",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("finding_id", sa.String(), nullable=True),
        sa.Column("statement", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["lab_findings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_claims", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lab_claims_finding_id"), ["finding_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lab_claims_project_id"), ["project_id"], unique=False)

    op.create_table(
        "lab_finding_reviews",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("finding_id", sa.String(), nullable=False),
        sa.Column("reviewer", sa.String(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["lab_findings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_finding_reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_finding_reviews_finding_id"), ["finding_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_finding_reviews_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "lab_claim_evidence",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("claim_id", sa.String(), nullable=False),
        sa.Column("excerpt_id", sa.String(), nullable=False),
        sa.Column("stance", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["lab_claims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["excerpt_id"],
            ["lab_source_excerpts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["lab_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_claim_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_claim_evidence_claim_id"), ["claim_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_claim_evidence_excerpt_id"), ["excerpt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lab_claim_evidence_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("lab_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("retry_of_run_id", sa.String(), nullable=True))
        # The server default safely backfills legacy runs before the application
        # begins supplying its Python-side default for new rows.
        batch_op.add_column(
            sa.Column("attempt", sa.Integer(), server_default=sa.text("1"), nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_lab_runs_retry_of_run_id"), ["retry_of_run_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_lab_runs_retry_of_run_id_lab_runs",
            "lab_runs",
            ["retry_of_run_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_runs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_lab_runs_retry_of_run_id_lab_runs", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_lab_runs_retry_of_run_id"))
        batch_op.drop_column("attempt")
        batch_op.drop_column("retry_of_run_id")

    with op.batch_alter_table("lab_claim_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_claim_evidence_project_id"))
        batch_op.drop_index(batch_op.f("ix_lab_claim_evidence_excerpt_id"))
        batch_op.drop_index(batch_op.f("ix_lab_claim_evidence_claim_id"))

    op.drop_table("lab_claim_evidence")
    with op.batch_alter_table("lab_finding_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_finding_reviews_project_id"))
        batch_op.drop_index(batch_op.f("ix_lab_finding_reviews_finding_id"))

    op.drop_table("lab_finding_reviews")
    with op.batch_alter_table("lab_claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_claims_project_id"))
        batch_op.drop_index(batch_op.f("ix_lab_claims_finding_id"))

    op.drop_table("lab_claims")
    with op.batch_alter_table("lab_model_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_model_calls_stage"))
        batch_op.drop_index(batch_op.f("ix_lab_model_calls_run_id"))
        batch_op.drop_index(batch_op.f("ix_lab_model_calls_project_id"))
        batch_op.drop_index(batch_op.f("ix_lab_model_calls_model"))
        batch_op.drop_index(batch_op.f("ix_lab_model_calls_agent_id"))

    op.drop_table("lab_model_calls")
    with op.batch_alter_table("lab_meeting_outcomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_meeting_outcomes_run_id"))
        batch_op.drop_index(batch_op.f("ix_lab_meeting_outcomes_project_id"))
        batch_op.drop_index(batch_op.f("ix_lab_meeting_outcomes_meeting_id"))

    op.drop_table("lab_meeting_outcomes")
    with op.batch_alter_table("lab_task_source_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_task_source_links_task_id"))
        batch_op.drop_index(batch_op.f("ix_lab_task_source_links_source_id"))
        batch_op.drop_index(batch_op.f("ix_lab_task_source_links_project_id"))

    op.drop_table("lab_task_source_links")
    with op.batch_alter_table("lab_task_dependencies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_task_dependencies_task_id"))
        batch_op.drop_index(batch_op.f("ix_lab_task_dependencies_project_id"))
        batch_op.drop_index(batch_op.f("ix_lab_task_dependencies_depends_on_task_id"))

    op.drop_table("lab_task_dependencies")
    with op.batch_alter_table("lab_evaluation_scores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_evaluation_scores_candidate_id"))

    op.drop_table("lab_evaluation_scores")
    with op.batch_alter_table("lab_action_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_action_items_promoted_task_id"))
        batch_op.drop_index(batch_op.f("ix_lab_action_items_project_id"))
        batch_op.drop_index(batch_op.f("ix_lab_action_items_owner_agent_id"))
        batch_op.drop_index(batch_op.f("ix_lab_action_items_meeting_id"))

    op.drop_table("lab_action_items")
    with op.batch_alter_table("lab_source_excerpts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_source_excerpts_source_id"))
        batch_op.drop_index(batch_op.f("ix_lab_source_excerpts_quote_sha256"))
        batch_op.drop_index(batch_op.f("ix_lab_source_excerpts_project_id"))

    op.drop_table("lab_source_excerpts")
    with op.batch_alter_table("lab_evaluation_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_evaluation_candidates_project_id"))
        batch_op.drop_index(batch_op.f("ix_lab_evaluation_candidates_experiment_id"))

    op.drop_table("lab_evaluation_candidates")
    with op.batch_alter_table("lab_trace_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_trace_links_target_id"))
        batch_op.drop_index(batch_op.f("ix_lab_trace_links_source_id"))
        batch_op.drop_index(batch_op.f("ix_lab_trace_links_project_id"))

    op.drop_table("lab_trace_links")
    with op.batch_alter_table("lab_source_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_source_documents_project_id"))
        batch_op.drop_index(batch_op.f("ix_lab_source_documents_content_sha256"))

    op.drop_table("lab_source_documents")
    op.drop_table("lab_project_policies")
    with op.batch_alter_table("lab_evaluation_experiments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_evaluation_experiments_project_id"))

    op.drop_table("lab_evaluation_experiments")
    with op.batch_alter_table("lab_automation_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_automation_runs_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_lab_automation_runs_project_id"))

    op.drop_table("lab_automation_runs")
    with op.batch_alter_table("lab_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_templates_name"))
        batch_op.drop_index(batch_op.f("ix_lab_templates_kind"))

    op.drop_table("lab_templates")
    # ### end Alembic commands ###
